### ISSUE TITLE
session not consistent 

### ISSUE THREAD

**Issue by dagisky** [seanmcgary/session-store#1]
Hey I am using your session-store to store my session on redis db and at some time I could not set a session data.. I have to restart the server to be able to set the session data ... here are my conf 

var SS = require('session-store');
........
var SessionManager = new SS.Manager(new SS.RedisStore({host:env.redisdb.hostname, port:env.redisdb.port, prefix:'chs-sess'}));
......
app.use(new SS.Middleware({
    sessionManager: SessionManager,
    cookieKey: 'my cookie key',
    salt: 'my salt'
}));

and I use 
exports.logOut = function (req, res) {
    req.session.destroy();
    req.session.flush();
    res.redirect('/auth/logIn');
}
for destroying the session and I use 
   req.session.flush();  
   req.session.set(result);
for setting the session 
result is JSON obj

I am using Express 3 ... please help on this ....

**Comment by seanmcgary** [comment]
Are you setting `req.session` within your route handler, because thats where it should be set.

Example:

``` javascript
app.get('/some-route', function(req, res){
    console.log(req.session); // --> should be an object
    req.session.someKey = 'someValue';

   res.send(200);
});

app.get('/after-some-route', function(req, res){
    console.log(req.session); // provided you hit "/some-route" first, this should be { someKey: "someValue" }

    res.send(200);
});
```

**Comment by dagisky** [comment]
on my app.js I have 

``` javascript
var app = express(); 
.....
var SS = require('session-store');
var routes = require('./routes/index');
........
var SessionManager = new SS.Manager(new SS.RedisStore({host:env.redisdb.hostname, port:env.redisdb.port, prefix:'chs-sess'}));
......
app.use(new SS.Middleware({
sessionManager: SessionManager,
cookieKey: 'my cookie key',
salt: 'my salt'
}));
.....
app.use('/', routes);
```

and on my routes/index file I have 

``` javascript
var express = require('express');
var router = express.Router();
......
var auth = require('./auth');
.....
router.use('/auth/logOut', auth.logOut);  // for logging out 
.....
router.use('/auth/logIn', auth.index); // for logging in 

```

here on the auth file I have all the log in and log out 

``` javascript

exports.logOut = function (req, res) {
    req.session.destroy();
    req.session.flush();
    res.redirect('to log in page');
}

exports.index = function (req, res) {
console.log("the session data are:-");
    console.log(req.session.attributes);
    if (req.session.attributes.usertype != undefined) {
        // the user is already loged in so lead him/her to his/her profile page 
        res.redirect('user profile page');
    } else {
           /* the user is not logged in so check if username and password is posted and check it on db  then if it exists*/
          req.session.set(result); // result is JSON obj
   }
}
```

thus I guess it is within my route handler ...
Do I need to set a unique session  "string_id" for each session as ... 

``` javascript
var SessionManager = new SS.Manager(new SS.RedisStore({host:env.redisdb.hostname, port:env.redisdb.port, prefix:'chs-sess'} , string_id ));
```

Thank you for your fast reply ...

**Comment by seanmcgary** [comment]
Looks like you have a number of problems. Firstly, you said you're using Express 3, but `express.Router` to my knowledge is only available in version 4.

I think you need to read up on how modules and scoping works (are you new to javascript/node by chance?) as the way you're requiring your routes is wrong.

Without the router:

_app.js_

``` javascript
var app = express(); 

var SS = require('session-store');
var routes = require('./routes/index');

var SessionManager = new SS.Manager(new SS.RedisStore({
    host: env.redisdb.hostname, 
    port: env.redisdb.port, 
    prefix: 'chs-sess'
}));

app.use(new SS.Middleware({
    sessionManager: SessionManager,
    cookieKey: 'my cookie key',
    salt: 'my salt'
}));

require('./routes')(app);
```

_routes/index.js_

``` javascript
var auth = require('./auth');

module.exports = function(app){
    app.get('/auth/logOut', auth.logOut);  // for logging out 
    app.get('/auth/logIn', auth.index); // for logging in 
};
```

This way you're passing your express server instance directly to your module.

---

With the router:
_app.js_

``` javascript
var app = express(); 

var SS = require('session-store');
var routes = require('./routes/index');

var SessionManager = new SS.Manager(new SS.RedisStore({
    host: env.redisdb.hostname, 
    port: env.redisdb.port, 
    prefix: 'chs-sess'
}));

app.use(new SS.Middleware({
    sessionManager: SessionManager,
    cookieKey: 'my cookie key',
    salt: 'my salt'
}));

app.get('/', require('./routes'));

```

_routes/index.js_

``` javascript
var router = require('express').Router();
var auth = require('./auth');

router.get('/auth/logOut', auth.logOut);  // for logging out
router.get('/auth/logIn', auth.index); // for logging in 

module.exports = router;
```

> Do I need to set a unique session "string_id" for each session as ...

`RedisStore` only takes one argument, so Im not sure why you're thinking it takes a second.

**Comment by dagisky** [comment]
yes I only started node few months ago...
would my code work on express4

**Comment by seanmcgary** [comment]
If you want to specifically use the router, then yeah, use Express 4. The first example I provided _should_ work on both 3 and 4 as it doesnt rely on the router.

**Comment by EskenderTamrat** [comment]
hey Sean,

I encountered a same problem, and I am using Express 4. I consistently have to restart the server for storing the session data.

Thanks

**Comment by seanmcgary** [comment]
Heres an example that works. Essentially, it assigns a UUID to the session if it doesnt exist and logs it to the console after the response is sent (thus meaning the session is flushed to redis). If you load the page in two different browsers (or using incognito mode) you'll see that each browser session persists the UUID its been assigned.

``` javascript
var express = require('express');
var SS = require('session-store');
var cookieParser = require('cookie-parser');
var uuid = require('node-uuid');

var server = express();

var SessionManager = new SS.Manager(new SS.RedisStore());

server.use(cookieParser());

server.use(new SS.Middleware({
    sessionManager: SessionManager,
    cookieKey: 'my-cookie-key',
    salt: 'my-salt'
}));

server.get('/', function(req, res){
    if(!req.session.get('uuid')){
        req.session.set({ uuid: uuid.v4() });
    }
    res.send(200);
    console.log(req.session.get('uuid'));
});

server.listen(9000, function(){
    console.log('server running');
});
```

Not sure what you guys are doing wrong. Are you sure you have redis running correctly and the session store is connecting to it?

**Comment by seanmcgary** [comment]
To check and see if its getting flushed to redis properly, just grab `req.session.id` and run:

``` bash
redis-cli get <session id> | python -m json.tool
```
