### ISSUE TITLE
session-store Consistency on the Server

### ISSUE THREAD

**Issue by EskenderTamrat** [seanmcgary/session-store#2]
I am using session-store as a middleware for the session handling of my nodejs app running on a server. But after a day or two of working properly, the session data is consistently emptied & we couldn't login to the system accordingly. Only restarting the server would do the trick at this point.

I used the module appropriately, as mentioned in the documentation. Is there any issues with the server deployment of it happening before? Any suggestions why it needs a restart every two days?

Thanks.

**Comment by seanmcgary** [comment]
Can you provide me with an example of how you're using it? Sounds like there might be something wrong with the way you have cookies configured since the system relies on storing a unique key in a cookie which then looks up the actual record in redis. The record in redis is set with the `SET` command which does not set a TTL, so the key/value will persist until you replace it or until redis is flushed.

**Comment by EskenderTamrat** [comment]
Hi Sean,

I'm still searching for a fix on this one.

I'm using express 4.

My code snippet

# 

app.js

```
var express = require('express');
var cookieParser = require('cookie-parser');  
var bodyParser = require('body-parser');
var uuid = require('node-uuid');
var SS = require('session-store');
var routes = require('./routes/index');
var app = express(); // the server is created
app.use(cookieParser()); 
app.use(express.static(path.join(__dirname, 'public'))); 
app.use(expressValidator());

var SessionManager = new SS.Manager(new SS.RedisStore({host:env.redisdb.hostname, port:env.redisdb.port, prefix:'chs-sess', cookie: {
    maxAge: 3*24*60*60*1000 // 3 day, in milliseconds
}}));

app.use(new SS.Middleware({
    sessionManager: SessionManager,
    cookieKey: 'cookiekey',
    salt: 'saltkey'
}));
app.use('/', routes);
app.get('/', require('./routes'));

// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
 });

// error handlers for session handling
if (app.get('env') === 'production') {
    app.set('trust proxy', 1) // trust first proxy
}

app.get('/', function(req, res){
    if(!req.session.get('uuid')){
        req.session.set({ uuid: uuid.v4() });
    }
    res.send(200);
    console.log(req.session.get('uuid'));
});

app.listen(9000, function(){
    console.log('server running');
});

module.exports = app;
```

# 

routes/index.js

```
var router = require('express').Router();
var auth = require('./auth');
router.get('/auth/logOut', auth.logOut);  // for logging out
router.get('/auth/logIn', auth.index); // for logging in 
module.exports = router;
```

# 

auth.js

```
exports.index = function (req, res) {
    console.log("the session data are:-");
    console.log(req.session.attributes);
    if (req.session.attributes.usertype != undefined) {
        // the user is already loged in so lead him/her to his/her profile page 
        res.redirect(req.headers['referer']);
    } else {
        if (req.body.username != undefined && req.body.password != undefined) {
            var query = "MATCH (n {username:'"+req.body.username.trim()+"', password:'"+sha1(req.body.password)+"'}) return n";
                console.log('query');
                console.log(query);
                var user = db.query(query, function (err, result) {
                    console.log("the result I found");

                    if (err) {
                        res.render('auth/logIn', {title: "LogIn", error: "wrong username and password combination..."});
                    } else if (result[0] != undefined) {
                        req.session.flush();
                        result[0].password = undefined;
                        req.session.set(result[0]);
                        console.log("the session are:-");
                        console.log(req.session.attributes);
                        res.redirect('/' + req.session.attributes.usertype);
                    } else {
                        res.render('auth/logIn', {title: "LogIn", error: "wrong username and password combination..."});
                    }
                });
            }
        } else {
            res.render('auth/logIn', {title: "LogIn", error: res.("Please fill the fields")});
        }
    }
}
```

# 

Now this works on a server I deployed into, but after one day, it will block login to the system. (Tried on two different servers). When this happen, the system print the last else statement in 'auth.js' in the middle of conducting the 'if', which is very weird.

Any suggestions?

Many thanks for following this up.

**Comment by seanmcgary** [comment]
So a few things I see here:

```
} else if (result[0] != undefined) {
    req.session.flush();
    result[0].password = undefined;
    req.session.set(result[0]);
    console.log("the session are:-");
    console.log(req.session.attributes);
    res.redirect('/' + req.session.attributes.usertype);
} else {
```

The only time that you should call `session.flush` is when you want to manually sync data to redis, otherwise its called automatically when you call `res.send`. So there could be some race condition with that.

```
req.session.attributes.usertype != undefined
```

You should really be using `req.session.get('usertype');`.

Also, can you verify that:
1. The session cookie is actually present in your browser
2. The expected values are being persisted to redis correctly?

**Comment by seanmcgary** [comment]
``` javascript
var SessionManager = new SS.Manager(new SS.RedisStore({
    host:env.redisdb.hostname, 
    port:env.redisdb.port, 
    prefix:'chs-sess', 
    cookie: {
        maxAge: 3*24*60*60*1000 // 3 day, in milliseconds
    }
}));
```

Your cookie config is also in the wrong place. That should be passed to the middleware, not the session manager. The default TTL is 1 day, so thats probably your problem:

https://github.com/seanmcgary/session-store/blob/master/lib/express.js#L21

**Comment by EskenderTamrat** [comment]
Thanks, @seanmcgary. I updated my code per your pointers (about the session.flush, avoiding possible race conditions, and removing the cookie config from the session manager), but it seems the default TTL is the reason for it to loss the session data after running for a day. I set the parameter to false, and I guess that solves it. Thanks for your ongoing cooperation.
